name : E2E Tests

on:
  workflow_dispatch:

jobs:
  E2E_Chrome_Test:
    runs-on: windows-latest
    permissions:
      checks: write


    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: setup java jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: SetupMaven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Execute Tests
        run: mvn -Dtest="POM_Tests.AutomationExerciseTests" test

      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Report Edge_Windows
          path: 'target/surefire-reports/Test-*.xml'
          reporter: java-junit
