name: E2E Tests

on:
  workflow_dispatch:
    inputs:
      testsPath:
        description: 'Path to Tests to be Executed'
        required: false
        default: 'POM_Tests.AutomationExerciseTests'
      WindowsBrowser:
        description: 'Browser for Windows'
        required: false
        default: 'edge'
      UbuntuBrowser:
        description: 'Browser for Ubuntu'
        required: false
        default: 'chrome'

  #schedule:
    #- cron: "*/35 * * * *"  # Every 35 minutes

  pull_request:
    branches:
      - main

jobs:
  E2E_Test_Windows:
    name: E2E Tests on Windows
    runs-on: windows-latest
    permissions:
      checks: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Execute Windows Tests
        run: mvn -DBrowserName="${{ github.event.inputs.WindowsBrowser || 'edge' }}" -Dtest="${{ github.event.inputs.testsPath }}" test

      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Tests Report Windows ${{ github.event.inputs.WindowsBrowser || 'edge' }}
          path: target/surefire-reports/TEST-*.xml
          reporter: java-junit

      - name: Generate Allure Report
        continue-on-error: true
        run: mvn allure:report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: Allure Report Windows ${{ github.event.inputs.WindowsBrowser || 'edge' }}
          path: target/site/allure-maven-plugin/index.html

  E2E_Test_Ubuntu:
    name: E2E Tests on Ubuntu
    runs-on: ubuntu-latest
    permissions:
      checks: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Execute Ubuntu Tests
        run: mvn -DBrowserName="${{ github.event.inputs.UbuntuBrowser || 'chrome' }}" -DHeadLessBrowsing=true -Dtest="${{ github.event.inputs.testsPath }}" test

      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Tests Report Ubuntu ${{ github.event.inputs.UbuntuBrowser || 'chrome' }}
          path: target/surefire-reports/TEST-*.xml
          reporter: java-junit

      - name: Generate Allure Report
        continue-on-error: true
        run: mvn allure:report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: Allure Report Ubuntu ${{ github.event.inputs.UbuntuBrowser || 'chrome' }}
          path: target/site/allure-maven-plugin/index.html
