on:
  workflow_dispatch:
    inputs:
      testsPath:
        description: 'Path to Tests to be Executed'
        default: ''

  schedule:
    - cron: "28 20 * * *" # Runs at 10:15 PM Cairo Time (8:15 PM UTC)

jobs:
  E2E_Test:
    runs-on: windows-latest
    permissions:
      checks: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Execute Tests
        run: |
          if [ -z "${{ github.event.inputs.testsPath }}" ]; then
            echo "No test path provided. Running default tests: POM_Tests.AutomationExerciseTests..."
            mvn -Dtest="POM_Tests.AutomationExerciseTests" test
          else
            echo "Running specific tests from path: ${{ github.event.inputs.testsPath }}"
            mvn -Dtest="${{ github.event.inputs.testsPath }}" test
          fi

      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit
